<a href="https://colab.research.google.com/github/shivamsingh163248/Data_Mining_and_Warehousing_CSBM505_M.Tech_NIT-D/blob/main/LAB%206/covaraince_chisqure_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#importing file
import numpy as np


In [4]:
#creating the random arrys
arr = np.random.rand(4)

In [5]:
print(arr)

[0.25890344 0.59356697 0.81462024 0.83237981]


In [7]:
#again creating the second arays
arr1 = np.random.randint(100 , size=4)
print(arr1)

[92  0 54 52]


In [8]:
#find the covarianc
covariance = np.cov(arr1 , arr)
print(covariance)

[[ 1.42766667e+03 -4.21047603e+00]
 [-4.21047603e+00  7.13256253e-02]]


In [14]:
from scipy.stats import chi2_contingency

# defining the table
data = [[207, 282, 241], [234, 242, 232]]
stat, p, dof, expected = chi2_contingency(data)
print(str(p))


0.1031971404730939
